### ISSUE TITLE
Task 'Certification' not found in root project 'web-api-commander'.

### ISSUE THREAD

**Issue by RohaanA** [RESOStandards/reso-certification-utils#197]
Hi, 

I am trying to run the RESO Certification Tool for testing our Odata API. I have setup both the utility tool as well as the commander tool and setup the .env file as such
![image](https://github.com/user-attachments/assets/605ee16f-e106-4374-b897-c006c4524ded)

but when I run the reso util tool using this command 

`reso-certification-utils runDDTests -v 1.7 -p config.json -l 100 -a`

I get the error, 

![image](https://github.com/user-attachments/assets/2057ca27-bee0-4293-9091-f88d04d81676)

I am using Windows 11 with Oracle JDK 17

**Comment by darnjo** [comment]
The paths shouldn't be quoted. You should also probably use the absolute path to the Commander. You should be able to change into that directory and run gradlew tasks and see tasks if the Commander is set up correctly on your machine. You can also use Docker if it's not working. See the instructions on the main README.

**Comment by RohaanA** [comment]
> The paths shouldn't be quoted. You should also probably use the absolute path to the Commander. You should be able to change into that directory and run gradlew tasks and see tasks if the Commander is set up correctly on your machine. You can also use Docker if it's not working. See the instructions on the main README.

Alright, I was also trying to use Commander and run into this error.

![image](https://github.com/user-attachments/assets/6c29dbc7-3960-46cf-8dde-bbff55db6095)


The file does exist, so I am assuming there is some issue in the file path being encoded with %20? Is this a known issue?

**Comment by darnjo** [comment]
Seems like an installation or config issue on your local machine. Please
use Docker or email dev at reso for support.
