### ISSUE TITLE
Schema Validation Issues

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/reso-certification-utils#94]
Please address the following:
- [x] Max lengths are generating warnings for strings when the `maxLength` attribute is present. Schema validation utils shouldn't be validating properties such as this. When something like string max length is to be enforced, then if the max length property is present or unknown, enforce it. Otherwise just enforce that there's string data in the field but don't enforce string lengths. 
- [ ] Integers are being flagged incorrectly. There are only three sizes of integer possible for Web API certifications: Int16, Int32, and Int64. These items are, optionally, nullable. And if there's anything besides integer data in an integer field, the tests should fail. 
- [x] Regarding integers, for RESO Common Format certification, rather than Int16, Int32, or Int64, validation should fail if there's non-integer data in the field and warn (only once per field) if the size of the data in the field exceeds the DD suggested max length, which should be in the RESO reference metadata.
- [ ] For things like decimals, if there are valid decimal properties specified in the metadata then enforce them, but decimals can also be null. So, if the field is nullable it doesn't need to contain a decimal.

**Comment by darnjo** [comment]
Which of these items have been completed? Perhaps they can be checked off? 

Is this ready for a PR?

**Comment by mohit-s96** [comment]
Checked off the 2 points I have addressed. Couldn't replicate the other 2 points locally (limited data). Added tests for the changes.
