### ISSUE TITLE
Create Reference Variations CSV and README

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/reso-certification-utils#97]
We need to formalize and document the Fast Track CSV template in order to submit suggestions to the Variations Service using CSV rather than JSON. 

There's a CLI / library option for it here: https://github.com/RESOStandards/reso-certification-utils/blob/main/lib/variations/README.md#update-variations-admin, which uses the most recent Fast Track sheets. 

The goal is to produce the following:
- [x] Sheet template CSV called `variations-template.csv`.
- [ ] For each artifact, when applicable, create a directory called `./lib/main/variations/artifacts/{artifact-name}/README.md` with all relevant artifacts in that directory explaining what they are in more detail. Example (from project root): Directory would be, `./lib/main/variations/artifacts/variations-service/` which would contain `./lib/main/variations/artifacts/variations-service/README.md`.
- [ ] `README.md` in root of `./lib/main/variations/artifacts` subdirectory outlining what each artifact is, which links to more specific the info, when applicable. Otherwise just a summary if it can fit into 1-2 sentences.

**Comment by Jad212s** [comment]
Below is the Fast Track sheet structure that was used on the first batch of suggestions for top used fields. We probably don't need anything related to usage metrics and comments as the mappings volunteered from other orgs won't have that.

[Fast-Track-Template-With-Usage-Comments-Fields.csv](https://github.com/RESOStandards/reso-certification-utils/files/14126242/Fast-Track-Template-With-Usage-Comments-Fields.csv)

Below is a structure with no comments or usage fields, if we'd want to use that instead.

[Fast-Track-Template-No-Usage-Comments-Fields.csv](https://github.com/RESOStandards/reso-certification-utils/files/14126254/Fast-Track-Template-No-Usage-Comments-Fields.csv)

**Comment by Jad212s** [comment]
Updated with the addition of Suggested Related Resource Name field.

[Fast-Track-Template-with-Usage-and-Comments-Fields.csv](https://github.com/RESOStandards/reso-certification-utils/files/14183209/Fast-Track-Template-with-Usage-and-Comments-Fields.csv)
[Fast-Track-Template-No-Usage-No-Comments-Fields.csv](https://github.com/RESOStandards/reso-certification-utils/files/14183216/Fast-Track-Template-No-Usage-No-Comments-Fields.csv)

**Comment by darnjo** [comment]
Variations Template is here.

[VariationsTemplate.csv](https://github.com/user-attachments/files/16237439/VariationsTemplate.csv)
